name: Release Helm Chart

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Package chart
        run: |
          helm package .

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: Update Helm repo index
        run: |
          cp registry-mirror-*.tgz gh-pages/
          cd gh-pages
          helm repo index . --url https://aminmokhtari94.github.io/registry-mirror/
          git add .
          git commit -m "Release ${{ github.ref_name }}"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: registry-mirror-*.tgz
          generate_release_notes: true
